# Generated by Django 4.1.3 on 2022-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
