# Generated by Django 4.1.3 on 2022-12-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
