# Generated by Django 4.1.3 on 2022-12-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
