# Generated by Django 4.1.3 on 2022-12-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places_remember_app', '0006_alter_userprofile_avatar_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(default='/static/images/default_avater.png'),
        ),
    ]
